perf: Optimize lookup for the next deployment by narrowing search
mendersoftware/deployments pull request #1026
Opened 2024-06-11 13:20 UTC by alfrunes

2024-06-12 18:58 UTC, kjaskiewiczz requested changes
There is no support for dynamic deployments here, so please update the code and commit message. Except for that it's looking good.

2024-06-12 18:58 UTC, kjaskiewiczz commented on store/mongo/datastore_mongo.go
> +// after createdAfter for which is either dynamic (requires post processing)
We do not support dynamic deployments here (the code is OK, it's only the comment which is wrong).

2024-06-12 18:58 UTC, kjaskiewiczz commented on store/mongo/datastore_mongo.go
> +	StorageKeyDeploymentDynamic             = "dynamic"
no dynamic deployments here

2024-06-13 07:09 UTC, alfrunes commented
> There is no support for dynamic deployments here, so please update the code and commit message. Except for that it's looking good.

Right, thanks. I actually just backported the commit from enterprise. I'll trim the dynamic deployments references from this PR.

2024-06-13 07:32 UTC, alfrunes commented
@mender-test-bot start pipeline --fast

2024-06-13 10:19 UTC, kjaskiewiczz approved these changes

2024-06-13 12:29 UTC, merged