Check for res before accessing its contents
mendersoftware/deployments pull request #597
Opened 2021-06-11 08:55 UTC by prashanthjbabu

Changelog: Commit
Signed-off-by: Prashanth Joseph Babu <prashanthjbabu@gmail.com>

Fix for crash : 
```
runtime error: invalid memory address or nil pointer dereference
goroutine 10955815 [running]:
runtime/debug.Stack(0xc001664ba8, 0x100afa0, 0x1c4a480)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/ant0ine/go-json-rest/rest.(*RecoverMiddleware).MiddlewareFunc.func1.1(0x1cb7580, 0x150a460, 0xc044c2a3c0)
        /go/src/github.com/mendersoftware/deployments/vendor/github.com/ant0ine/go-json-rest/rest/recover.go:41 +0x5a
panic(0x100afa0, 0x1c4a480)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/mendersoftware/deployments/store/mongo.(*DataStoreMongo).SetDeploymentStatus(0xc0003a2020, 0x150a2e0, 0xc044c2a750, 0xc03a2340c0, 0x24, 0x1147efe, 0xa, 0xc02897bdf0657a47, 0x4b82f713ccde, 0x1cb9be0, ...)
        /go/src/github.com/mendersoftware/deployments/store/mongo/datastore_mongo.go:1903 +0x376
github.com/mendersoftware/deployments/app.(*Deployments).recalcDeploymentStatus(0xc0002d6050, 0x150a2e0, 0xc044c2a750, 0xc066cbe840, 0x24, 0xc066cbe840)
        /go/src/github.com/mendersoftware/deployments/app/app.go:1291 +0xcc
github.com/mendersoftware/deployments/app.(*Deployments).UpdateDeviceDeploymentStatus(0xc0002d6050, 0x150a2e0, 0xc044c2a750, 0xc03ea5b07f, 0x24, 0xc04120c480, 0x24, 0xc04b13a668, 0x7, 0x0, ...)
        /go/src/github.com/mendersoftware/deployments/app/app.go:1277 +0x4f7
github.com/mendersoftware/deployments/api/http.(*DeploymentsApiHandlers).PutDeploymentStatusForDevice(0xc0002e0000, 0x150a460, 0xc044c2a3c0, 0xc0118acf80)
        /go/src/github.com/mendersoftware/deployments/api/http/api_deployments.go:1123 +0x31f
github.com/ant0ine/go-json-rest/rest.(*router).AppFunc.func1(0x150a460, 0xc044c2a3c0, 0xc0118acf80)

```

RCA: `res.MatchedCount` was accessed even when `res` was `nil` when mongodb faced an error during updation of document

Fix : Only access `res.MatchedCount` if `res` is not `nil`

2021-07-09 06:12 UTC, prashanthjbabu commented
@kjaskiewiczz @lluiscampos Can you please take a look at this ?

2021-07-09 07:59 UTC, kjaskiewiczz approved these changes
looks good

2021-07-09 11:26 UTC, lluiscampos approved these changes

2021-07-09 11:28 UTC, lluiscampos requested changes
The code looks good. Thanks for your contribution!

The `changelog: commit` however, I think is excessive. We use this only on very important fixes that require a lot of information for the user. Can you please change to something simple like: `Changelog: datastore_mongo: fix nil pointer dereference`

2021-07-12 03:59 UTC, prashanthjbabu commented
> The code looks good. Thanks for your contribution!
> 
> The `changelog: commit` however, I think is excessive. We use this only on very important fixes that require a lot of information for the user. Can you please change to something simple like: `Changelog: datastore_mongo: fix nil pointer dereference`

@lluiscampos I've changed the `Changelog` as requested.

2021-07-19 08:42 UTC, lluiscampos approved these changes

2021-07-19 08:47 UTC, kjaskiewiczz commented
@mender-test-bot start pipeline

2021-07-19 12:41 UTC, merged