fix: new field: Started in the device deployment struct.
mendersoftware/deployments pull request #955
Opened 2023-11-03 07:06 UTC by merlin-northern

Introduce a new field that denotes a time when device actually asked for a deployment.

Changelog: Title
Ticket: MEN-6793

2023-11-03 07:34 UTC, merlin-northern commented
@tranchitella I need initial review on this one. does it sound like a reasonable approach?

2023-11-06 12:47 UTC, tranchitella requested changes
I'm not sure that this is the right approach. By the way, there is something strange in the management of the `Created`, see here:
https://github.com/mendersoftware/deployments/blob/master/app/app.go#L1413

However, when we initialize the device deployment, we set `Created` to now:
https://github.com/mendersoftware/deployments/blob/master/model/device_deployment.go#L269

Your implementation has a drawback: it will issue a new (update) query when the deployment starts. I'm wondering whether this needs to be effectively done only if the deployment was previously pending. If we are inserting the deployment, we can set it straight away in the Insert query.

Additionally, you need to update API docs.

2023-11-06 14:16 UTC, merlin-northern commented
> I'm not sure that this is the right approach. By the way, there is something strange in the management of the `Created`, see here: https://github.com/mendersoftware/deployments/blob/master/app/app.go#L1413
> 
> However, when we initialize the device deployment, we set `Created` to now: https://github.com/mendersoftware/deployments/blob/master/model/device_deployment.go#L269
> 
> Your implementation has a drawback: it will issue a new (update) query when the deployment starts. I'm wondering whether this needs to be effectively done only if the deployment was previously pending. If we are inserting the deployment, we can set it straight away in the Insert query.
> 
> Additionally, you need to update API docs.

thank you. fixed. I will try to take a look at the `Created` field, but this one is about started, so maybe when we change GUI to show it next to the `Started` label we do not have to fix `Created` in this PR? if you consider checking `Created` field handling as a part of this task, let me know I will regroup.

2023-11-07 07:23 UTC, merlin-northern commented on store/mongo/datastore_mongo.go
> +	}
wow. I am sorry. it is a lesson to me: never send code from PTO with your head somewhere completely else. I am fixing.

2023-11-07 08:59 UTC, merlin-northern commented on store/mongo/datastore_mongo.go
> +	}
I will just take my time, testing properly, and fix. sorry for wasting your time.

2023-11-07 08:59 UTC, merlin-northern commented on store/mongo/datastore_mongo.go
> +	}
I will just take my time, testing properly, and fix. sorry for wasting your time.

2023-11-11 11:01 UTC, tranchitella approved these changes

2023-11-13 07:10 UTC, merged